# Generated by Django 4.0.3 on 2022-03-13 13:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kid',
            fields=[
                ('kid_id', models.BigIntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('kid_name', models.CharField(max_length=30)),
                ('kid_age', models.IntegerField()),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('parents_email_id', models.EmailField(max_length=254)),
            ],
        ),
    ]
