# Generated by Django 4.0.3 on 2022-03-13 13:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kids', '0002_alter_kid_kid_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kid',
            name='phone_number',
            field=models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
