# Generated by Django 4.0.3 on 2022-03-14 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kids', '0007_alter_images_updated_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='updated_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
