# Generated by Django 4.0.3 on 2022-03-14 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kids', '0008_alter_images_updated_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='food_group',
            field=models.CharField(choices=[('Veg', 'Veg'), ('Fruit', 'Fruit'), ('Grain', 'Grain'), ('Protein', 'Protein'), ('Dairy', 'Dairy'), ('Confectionery', 'Confectionery'), ('Unknown', 'Unknown')], max_length=20),
        ),
    ]
