# Generated by Django 4.0.3 on 2022-03-15 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kids', '0009_alter_images_food_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='food_image',
            field=models.ImageField(default=0, upload_to='images/'),
            preserve_default=False,
        ),
    ]
