# Generated by Django 4.0.3 on 2022-03-15 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kids', '0010_images_food_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='food_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='images',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
