# Generated by Django 4.0.3 on 2022-03-15 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kids', '0011_alter_images_food_image_alter_images_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image_url',
            field=models.URLField(default=0),
            preserve_default=False,
        ),
    ]
