# Generated by Django 4.0.3 on 2022-03-15 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kids', '0012_alter_images_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='food_image',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='images',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
