# Generated by Django 4.0.3 on 2022-03-15 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kids', '0013_alter_images_food_image_alter_images_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='is_approved',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
